---
name: Ansible Playbook

on:
  workflow_call:
    inputs:
      runs-on:
        description: Which image to use for this workflow.
        required: false
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
        default: ubuntu-latest
      python-version:
        description: Comma seperated list of python versions to use.
        default: "3.10,3.11"
        type: string
        required: false
      requirements-path:
        description: Path to the project's requirements.txt file.
        required: false
        type: string
        default: requirements.txt
      playbook-path:
        description: Path to the project's playbook to run.
        required: false
        type: string
        default: playbook.yml

jobs:
  ansible-playbook:
    runs-on: ${{ inputs.runs-on }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: join(inputs.python-version, ',')

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ${{ github.event.repository.name }}/${{ inputs.requirements-path }}
      - name: Run ansible-playbook
        run: |
          ansible-playbook ${{ github.event.repository.name }}/${{ inputs.playbook-path }}
