---
name: pdk validate

on:
  workflow_call:
    inputs:
      ruby_version:
        description: The version of ruby to use
        required: false
        default: "3.1.0"
        type: string

jobs:
  validate:
    name: pdk validate
    runs-on: ubuntu-latest

    steps:
      # This is required for the newest releases of litmus which depends
      # on the ffi gem.
      - name: Install libffi-dev
        run: sudo apt-get update && sudo apt-get install libffi-dev

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby_version }}
          bundler-cache: true

      - name: Install pdk
        run: gem install pdk

      - name: Bundle install
        run: bundle install

      - name: Run pdk validate
        run: pdk validate
